---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
spec:
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      initContainers:
        - name: wait-for-config-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z config-service-svc 80; do echo "Waiting for Config Service"; sleep 2; done',
            ]
      containers:
        - name: api-gateway-app
          image: axeloooo/api-gateway:latest
          ports:
            - containerPort: 8888
          livenessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:5000",
                  "-connect-timeout=100ms",
                  "-rpc-timeout=150ms",
                ]
            initialDelaySeconds: 5
          env:
            - name: REGISTRY_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: REGISTRY_SERVICE_URI
            - name: CONFIG_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: CONFIG_SERVICE_URI
            - name: ZIPKIN_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: zipkin-cm
                  key: ZIPKIN_SERVICE_URI

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  selector:
    app: api-gateway-app
  ports:
    - port: 80
      targetPort: 8888
