---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-app
spec:
  selector:
    matchLabels:
      app: config-service-app
  template:
    metadata:
      labels:
        app: config-service-app
    spec:
      initContainers:
        - name: wait for eureka
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z eureka-svc 8761; do echo "Waiting for Eureka"; sleep 2; done',
            ]
      containers:
        - name: config-service-app
          image: axeloooo/config-service:latest
          resources:
            limits:
              cpu: "60m"
              memory: "256Mi"
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: REGISTRY_SERVICE_URI

---
apiVersion: v1
kind: Service
metadata:
  name: config-service-svc
spec:
  selector:
    app: config-service-app
  ports:
    - port: 80
      targetPort: 8080
