---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:5000",
                  "-connect-timeout=100ms",
                  "-rpc-timeout=150ms",
                ]
            initialDelaySeconds: 5
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: pgadmin-cm
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pgadmin-cm
                  key: PGADMIN_DEFAULT_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
