---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z postgres-svc 5432; do echo "Waiting for Postgres"; sleep 2; done',
            ]
      containers:
        - name: eureka
          image: axeloooo/registry-service:latest
          ports:
            - containerPort: 8761
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - port: 8761
      name: eureka

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-rest-svc
spec:
  selector:
    app: eureka
  ports:
    - port: 80
      targetPort: 8761
