---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: task-service-app
  template:
    metadata:
      labels:
        app: task-service-app
    spec:
      initContainers:
        - name: wait-for-config-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z config-service-svc 80; do echo "Waiting for Config Service"; sleep 2; done',
            ]
      containers:
        - name: task-service-app
          image: axeloooo/task-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REGISTRY_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: REGISTRY_SERVICE_URI
            - name: CONFIG_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: CONFIG_SERVICE_URI
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: DB_HOST
            - name: ZIPKIN_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: zipkin-cm
                  key: ZIPKIN_SERVICE_URI

---
apiVersion: v1
kind: Service
metadata:
  name: task-service-svc
spec:
  selector:
    app: task-service-app
  ports:
    - port: 80
      targetPort: 8081
