---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-app
spec:
  selector:
    matchLabels:
      app: user-service-app
  template:
    metadata:
      labels:
        app: user-service-app
    spec:
      initContainers:
        - name: wait-for-config-service
          image: busybox
          command:
            [
              "sh",
              "-c",
              'until nc -z config-service-svc 80; do echo "Waiting for Config Service"; sleep 2; done',
            ]
      containers:
        - name: user-service-app
          image: axeloooo/user-service:latest
          resources:
            limits:
              cpu: "60m"
              memory: "256Mi"
          ports:
            - containerPort: 8086
          env:
            - name: REGISTRY_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: REGISTRY_SERVICE_URI
            - name: CONFIG_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: config-cm
                  key: CONFIG_SERVICE_URI
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-cm
                  key: DB_HOST
            - name: ZIPKIN_SERVICE_URI
              valueFrom:
                configMapKeyRef:
                  name: zipkin-cm
                  key: ZIPKIN_SERVICE_URI

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  selector:
    app: user-service-app
  ports:
    - port: 80
      targetPort: 8086
