server:
  port: 8761

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}.eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
