server:
  port: 8761

spring:
  application:
    name: registry-service

eureka:
  server:
    peer-node-read-timeout-ms: 10000
  instance:
    hostname: ${HOSTNAME:localhost}.eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
