server:
  port: 8080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${DOCKER_CONFIG_GITHUB_URL:https://github.com/Axeloooo/dev-choresync-config-service}
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URI:http://localhost:8761/eureka/}
