server:
  port: 8080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Axeloooo/choresync-config-service
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
