server:
  port: 8086

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://localhost:8080"
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root
