server:
  port: 8083

spring:
  application:
    name: assignment-service
  config:
    import: "optional:configserver:http://localhost:8080"
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/assignmentdb
    username: postgres
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-64868999.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaf8bdnawwBsjPiP5d7
            client-secret:
        provider:
          okta:
            issuer-uri: https://dev-64868999.okta.com/oauth2/default
