server:
  port: 8084

spring:
  application:
    name: userhousehold-service
  config:
    import: "optional:configserver:{CONFIG_SERVICE_URI:http://localhost:8080}"
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/userhouseholddb
    username: postgres
    password: root
